Repository Enterprise-CMCS/macpro-mdct-mfp, pull requests merged in 2024-04, with the labels that each got.

#512 Upgrade AWS SDK to v3
  package.json
  services/app-api/handlers/banners/create.test.ts
  services/app-api/handlers/banners/delete.test.ts
  services/app-api/handlers/banners/fetch.test.ts
  services/app-api/handlers/handler-lib.test.ts
  services/app-api/handlers/handler-lib.ts
  services/app-api/handlers/reports/approve.test.ts
  services/app-api/handlers/reports/archive.test.ts
  services/app-api/handlers/reports/create.test.ts
  services/app-api/handlers/reports/create.ts
  services/app-api/handlers/reports/fetch.test.ts
  services/app-api/handlers/reports/fetch.ts
  services/app-api/handlers/reports/release.test.ts
  services/app-api/handlers/reports/release.ts
  services/app-api/handlers/reports/submit.test.ts
  services/app-api/handlers/reports/update.test.ts
  services/app-api/package.json
  services/app-api/utils/auth/authorization.test.ts
  services/app-api/utils/auth/authorization.ts
  services/app-api/utils/constants/constants.ts
  services/app-api/utils/debugging/debug-lib.test.ts
  services/app-api/utils/debugging/debug-lib.ts
  services/app-api/utils/dynamo/convertToDynamoExpressionVars.test.ts
  services/app-api/utils/dynamo/convertToDynamoExpressionVars.ts
  services/app-api/utils/dynamo/dynamodb-lib.test.ts
  services/app-api/utils/dynamo/dynamodb-lib.ts
  services/app-api/utils/dynamo/hasReportPathParams.ts
  services/app-api/utils/formTemplates/formTemplates.test.ts
  services/app-api/utils/formTemplates/formTemplates.ts
  services/app-api/utils/logging/index.ts
  services/app-api/utils/other/other.ts
  services/app-api/utils/s3/s3-lib.test.ts
  services/app-api/utils/s3/s3-lib.ts
  services/app-api/utils/testing/mocks/mockReport.ts
  services/app-api/utils/testing/proxyEvent.ts
  services/app-api/utils/testing/setupJest.ts
  services/app-api/utils/types/other.ts
  services/app-api/yarn.lock
  services/ui-auth/handlers/createUsers.js
  services/ui-auth/libs/cognito-lib.js
  services/ui-src/package.json
  services/ui-src/yarn.lock
  services/uploads/src/libs/dynamodb-lib.js
  services/uploads/src/libs/handler-lib.js
  services/uploads/src/libs/response-lib.js
  yarn.lock
Labels: ready for review

#515 [CMDCT-3372] Add E2E test for workplan
  services/app-api/forms/wp.json
  services/ui-src/src/components/tables/EntityRow.tsx
  tests/cypress/e2e/wp/form.cy.js
  tests/cypress/support/form.js
Labels: ready for review

#517 Fix Disabled Field Color
  services/ui-src/src/components/forms/Form.tsx
Labels: ready for review

#508 [MDCT #3374] New create work plan flow
  services/app-api/handlers/reports/create.test.ts
  services/app-api/handlers/reports/create.ts
  services/app-api/package.json
  services/app-api/utils/other/other.test.ts
  services/app-api/utils/other/other.ts
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
  services/ui-src/src/components/modals/AddEditReportModal.tsx
  services/ui-src/src/components/modals/AddNewWorkPlanModal.test.tsx
  services/ui-src/src/components/modals/AddNewWorkPlanModal.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/constants.ts
  services/ui-src/src/forms/addEditWpReport/newWpReport.json
Labels: ready for review, design review, product review

#527 Update validation for optional fields in SAR
  services/app-api/forms/sar.json
Labels: ready for review

#511 Error alert refactor
  services/app-api/utils/types/other.ts
  services/app-api/utils/types/reportContext.ts
  services/ui-src/src/components/alerts/Alert.tsx
  services/ui-src/src/components/alerts/ErrorAlert.test.tsx
  services/ui-src/src/components/alerts/ErrorAlert.tsx
  services/ui-src/src/components/banners/AdminBannerProvider.tsx
  services/ui-src/src/components/forms/AdminBannerForm.tsx
  services/ui-src/src/components/logins/LoginCognito.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.tsx
  services/ui-src/src/components/pages/Admin/AdminPage.test.tsx
  services/ui-src/src/components/pages/Admin/AdminPage.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/components/reports/ReportProvider.test.tsx
  services/ui-src/src/components/reports/ReportProvider.tsx
  services/ui-src/src/types/other.ts
  services/ui-src/src/types/reportContext.ts
  services/ui-src/src/types/states.ts
  services/ui-src/src/utils/state/useStore.ts
  services/ui-src/src/utils/testing/mockReport.ts
  services/ui-src/src/utils/testing/setupJest.tsx
  services/ui-src/src/verbiage/errors.ts
Labels: ready for review

#516 3486 Content Updates
  services/app-api/forms/sar.json
  services/app-api/forms/wp.json
  services/app-api/utils/formTemplates/formTemplates.test.ts
  services/app-api/utils/testing/mocks/mockReport.ts
  services/ui-src/src/components/cards/EntityCardTopSection.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedRETTable.test.tsx
  services/ui-src/src/components/export/ExportedReportBanner.test.tsx
  services/ui-src/src/components/export/ExportedSectionHeading.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
  services/ui-src/src/components/tables/EntityStatusIcon.tsx
  services/ui-src/src/forms/adminDashSelector/adminDashSelector.ts
  services/ui-src/src/utils/statusing/getRouteStatus.ts
  services/ui-src/src/utils/testing/mockForm.tsx
  services/ui-src/src/utils/testing/mockFullReportJSON.tsx
  services/ui-src/src/verbiage/pages/accordion.ts
  services/ui-src/src/verbiage/pages/profile.ts
  services/ui-src/src/verbiage/pages/sar/sar-export.ts
  services/ui-src/src/verbiage/pages/sar/sar-review-and-submit.ts
  services/ui-src/src/verbiage/pages/wp/wp-export.ts
  services/ui-src/src/verbiage/pages/wp/wp-review-and-submit.ts
  tests/cypress/e2e/wp/dashboard.cy.js
  tests/cypress/support/form.js
Labels: ready for review, design review

#520 Add ensureAvailableReport to Cypress commands
  .github/workflows/deploy.yml
  services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
  tests/cypress.config.js
  tests/cypress/e2e/wp/dashboard.cy.js
  tests/cypress/e2e/wp/form.cy.js
  tests/cypress/support/commands.js
  tests/cypress/support/form.js
Labels: ready for review

#537 Fix Submit Container styling for Mobile View
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
Labels: ready for review

#543 clean up non-number report period
  services/app-api/handlers/reports/create.ts
  services/app-api/utils/transformations/transformations.ts
  services/ui-src/src/components/modals/AddEditReportModal.tsx
Labels: ready for review

#553 Upgrade cypress to resolve vulkan issue
  tests/package.json
  tests/yarn.lock
Labels: ready for review

#562 Update README.md
  README.md
Labels: ready for review

#545 cmdct-3411 and 3532 - MFP UI bugs
  services/ui-src/src/components/alerts/Alert.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/reports/DynamicModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/verbiage/pages/wp/wp-alerts.ts
Labels: ready for review

#540 One default target population must be applicable
  services/app-api/forms/wp.json
  services/app-api/utils/constants/constants.ts
  services/app-api/utils/data/data.ts
  services/app-api/utils/validation/completionStatus.test.ts
  services/app-api/utils/validation/completionStatus.ts
  services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.test.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/constants.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/testing/mockForm.tsx
  tests/cypress/support/commands.js
  tests/cypress/support/form.js
Labels: ready for review

#530 [#3531] Show edit button if the report type is SAR
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/overlays/EntityDetailsDashboardOverlay.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/reports/DynamicModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/OverlayModalPage.test.tsx
  services/ui-src/src/components/reports/OverlayModalPage.tsx
  services/ui-src/src/components/tables/EntityRow.test.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/getEntityStatus.test.ts
  services/ui-src/src/components/tables/getEntityStatus.tsx
  services/ui-src/src/utils/testing/mockForm.tsx
Labels: ready for review, design review

#564 Fix Users error on SAR dashboard
  services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/reports/ReportProvider.test.tsx
  services/ui-src/src/components/reports/ReportProvider.tsx
Labels: ready for review

#569 3541 - Change validation for quarterly projections in WP
  services/app-api/forms/wp.json
  services/app-api/utils/transformations/transformations.ts
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/utils/reports/entities.test.ts
  services/ui-src/src/utils/reports/entities.ts
Labels: ready for review, product review
