Repository Enterprise-CMCS/macpro-mdct-mfp, pull requests merged in 2024-05, with the labels that each got.

#568 [CMDCT-3501] Create e2e test for unlocking and resubmitting a workplan
  services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
  services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
  tests/cypress/e2e/wp/form.cy.js
Labels: ready for review

#570 Bump codeclimate action version
  .github/workflows/deploy.yml
Labels: ready for review

#577 [CMDCT-3579] Remove accordion items on the help page
  services/ui-src/src/verbiage/pages/help.ts
Labels: ready for review, product review

#581 [CMDCT-3537] Fix spacing on SAR additional achievements list items
  services/app-api/forms/sar.json
Labels: ready for review

#578 The 10 Minute Dev Login Experience Care Package
  services/ui-src/src/components/logins/LoginCognito.tsx
Labels: ready for review

#586 Upgrade MFP to Node 20
  .nvmrc
  package.json
  services/app-api/package.json
  services/app-api/serverless.yml
  services/app-api/yarn.lock
  services/database/package.json
  services/database/serverless.yml
  services/database/yarn.lock
  services/topics/serverless.yml
  services/ui-auth/serverless.yml
  services/ui-src/package.json
  services/ui-src/serverless.yml
  services/ui-src/yarn.lock
  services/ui/serverless.yml
  services/uploads/serverless.yml
  yarn.lock
Labels: ready for review

#588 [CMDCT-3415] Fix console errors in AppRoutes
  services/ui-src/src/components/app/AppRoutes.test.tsx
Labels: ready for review

#584 [CMDCT-3535] - Fix display value for currency data
  services/ui-src/src/components/export/ExportEntityDetailsTable.test.tsx
  services/ui-src/src/components/export/ExportEntityDetailsTable.tsx
  services/ui-src/src/utils/reports/entities.test.ts
  services/ui-src/src/utils/reports/entities.ts
Labels: ready for review, design review

#580 [3420, 3418] Fixing more console errors
  services/app-api/utils/testing/mocks/mockForm.ts
  services/ui-src/src/components/fields/ChoiceListField.test.tsx
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/TextAreaField.test.tsx
  services/ui-src/src/components/fields/TextField.test.tsx
  services/ui-src/src/components/fields/TextField.tsx
  services/ui-src/src/utils/testing/mockForm.tsx
Labels: ready for review

#593 Set up serverless compose
  package.json
  scripts/deploy.sh
  serverless-compose.yml
  services/app-api/serverless.yml
  services/topics/package.json
  services/topics/serverless.yml
  services/topics/yarn.lock
  services/ui-auth/serverless.yml
  services/ui-src/serverless.yml
  services/uploads/serverless.yml
  yarn.lock
Labels: ready for review

#597 add concurrently for cypress local
  tests/package.json
  tests/yarn.lock
Labels: ready for review

#594 [CMDCT-3596/3597] - Fix SAR RE&T Page submissions and heading size
  services/app-api/utils/validation/checkInputValidity.ts
  services/app-api/utils/validation/schemaMap.test.ts
  services/app-api/utils/validation/schemaMap.ts
  services/ui-src/src/components/fields/CheckboxField.tsx
  services/ui-src/src/components/reports/ReportProvider.tsx
Labels: ready for review

#598 ensure fields have disabled prop for non-state users
  services/ui-src/src/components/fields/DateField.tsx
  services/ui-src/src/components/fields/NumberField.tsx
  services/ui-src/src/components/fields/TextField.tsx
Labels: ready for review

#602 Remove tests that don't add value
  services/app-api/handlers/reports/fetch.test.ts
Labels: ready for review

#600 [CMDCT-3595] Refactor ReportPageIntro
  services/app-api/forms/sar.json
  services/ui-src/src/components/accordions/AccordionItem.tsx
  services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
  services/ui-src/src/components/reports/DynamicModalOverlayReportPage.tsx
  services/ui-src/src/components/reports/ReportPageIntro.tsx
Labels: design review

#610 Update accordion content and styling to be semantic html(er)
  services/ui-src/src/components/accordions/InstructionsAccordion.tsx
  services/ui-src/src/verbiage/pages/accordion.ts
Labels: ready for review

#617 remove old react-scripts references
  services/ui-src/package.json
  services/ui-src/src/global.d.ts
Labels: ready for review

#618 cleanup unused dependencies and files
  services/uploads/package.json
  services/uploads/src/api.js
  services/uploads/src/scan.js
  services/uploads/src/test.json
  services/uploads/yarn.lock
Labels: ready for review

#616 Demo separate modals per report type
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/modals/AddEditReportModal.test.tsx
  services/ui-src/src/components/modals/AddEditReportModal.tsx
  services/ui-src/src/components/modals/AddNewWorkPlanModal.tsx
  services/ui-src/src/components/modals/CreateSarModal.test.tsx
  services/ui-src/src/components/modals/CreateSarModal.tsx
  services/ui-src/src/components/modals/CreateWorkPlanModal.test.tsx
  services/ui-src/src/components/modals/CreateWorkPlanModal.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
  services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
  services/ui-src/src/utils/testing/mockReport.ts
Labels: ready for review
