Repository Enterprise-CMCS/macpro-mdct-mfp, pull requests merged in 2024-03, with the labels that each got.

#479 Fix branch validation
  .github/branch-name-validation.sh
Labels: ready for review, ready to merge

#475 Main -> Val
  .github/CODEOWNERS
  .github/branch-name-validation.sh
  .github/workflows/deploy.yml
  services/app-api/forms/sar.json
  services/app-api/forms/wp.json
  services/app-api/utils/transformations/transformations.test.ts
  services/app-api/utils/transformations/transformations.ts
  services/app-api/utils/validation/completionSchemas.ts
  services/app-api/utils/validation/schemaMap.ts
  services/ui-src/src/components/export/ExportEntityDetailsTable.test.tsx
  services/ui-src/src/components/export/ExportedModalDrawerReportSection.test.tsx
  services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
  services/ui-src/src/components/export/ExportedRETTable.tsx
  services/ui-src/src/components/export/ExportedReportFieldTable.test.tsx
  services/ui-src/src/components/export/ExportedReportFieldTable.tsx
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/components/modals/AddEditOverlayEntityModal.tsx
  services/ui-src/src/components/reports/OverlayModalPage.tsx
  services/ui-src/src/components/reports/ReportPageIntro.tsx
  services/ui-src/src/components/tables/EntityStatusIcon.tsx
  services/ui-src/src/components/tables/getEntityStatus.tsx
  services/ui-src/src/utils/other/parsing.test.tsx
  services/ui-src/src/utils/other/parsing.ts
  services/ui-src/src/utils/testing/mockFullReportJSON.tsx
  services/ui-src/src/verbiage/pages/accordion.ts
  services/ui-src/src/verbiage/pages/sar/sar-dashboard.ts
  services/ui-src/src/verbiage/pages/sar/sar-export.ts
  services/ui-src/src/verbiage/pages/wp/wp-alerts.ts
  services/ui-src/yarn.lock
  tests/README.md
  tests/cypress.config.js
  tests/cypress/README.md
  tests/cypress/cypress.config.js
  tests/cypress/e2e/accessibility/homePage.cy.js
  tests/cypress/e2e/login.cy.js
  tests/cypress/package.json
  tests/cypress/support/accessibility.js
  tests/cypress/support/commands.js
  tests/cypress/support/e2e.js
  tests/cypress/support/index.js
  tests/cypress/support/step_definitions/authentication.js
  tests/cypress/support/step_definitions/formInputs.js
  tests/cypress/support/step_definitions/navigation.js
  tests/package.json
  tests/yarn.lock
  yarn.lock
Labels: ready for review

#477 Add postman folder with collection, environment, and instructions
  .pre-commit-config.yaml
  README.md
  postman/MFP.postman_collection.json
  postman/MFP.postman_environment.json
  postman/README.md
Labels: ready for review

#481 CMDCT-3303 - Add Cypress tests for homepage, profile, and dashboard
  tests/cypress.config.js
  tests/cypress/e2e/footer.cy.js
  tests/cypress/e2e/home.cy.js
  tests/cypress/e2e/profile.cy.js
  tests/cypress/e2e/wp/dashboard.cy.js
  tests/cypress/support/commands.js
Labels: ready for review

#486 Always display default target populations in initiatives
  services/app-api/utils/data/data.test.ts
  services/app-api/utils/data/data.ts
  services/ui-src/src/utils/forms/forms.test.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/testing/mockEntities.tsx
Labels: ready for review, design review, product review

#491 Fix on TR Console Error
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedOverlayModalReportSection.tsx
  services/ui-src/src/components/tables/Table.tsx
Labels: ready for review

#492 Cmdct 3354 - change to styling to remove console error
  services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
  services/ui-src/src/components/overlays/EntityDetailsDashboardOverlay.tsx
Labels: ready for review

#483 [CMDCT-3366] - Unskip and split up accessibility tests
  tests/cypress/e2e/accessibility/admin.cy.js
  tests/cypress/e2e/accessibility/help.cy.js
  tests/cypress/e2e/accessibility/home.cy.js
  tests/cypress/e2e/accessibility/homePage.cy.js
  tests/cypress/e2e/accessibility/profile.cy.js
  tests/cypress/support/commands.js
Labels: ready for review

#498 Update WP Submission Due Date
  services/app-api/utils/time/time.test.ts
  services/app-api/utils/time/time.ts
Labels: ready for review

#504 [MFP] Add Copy Over Subtext to WP Dashboard
  services/app-api/handlers/reports/create.ts
  services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
  services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
  services/ui-src/src/types/reportContext.ts
  services/ui-src/src/utils/testing/mockReport.ts
  services/ui-src/src/utils/testing/setupJest.tsx
Labels: ready for review
