Repository Enterprise-CMCS/macpro-mdct-mfp, pull requests merged in 2024-06, with the labels that each got.

#620 Remove br tags from review and submit page; cleanup styling
  services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
  services/ui-src/src/verbiage/pages/sar/sar-review-and-submit.ts
  services/ui-src/src/verbiage/pages/wp/wp-review-and-submit.ts
Labels: ready for review

#624 remove br tags from add sar modal
  services/ui-src/src/forms/addEditSarReport/addEditSarReport.json
Labels: ready for review

#634 CMDCT-3679: Fix error alert on Transition page from showing all the time
  services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
  services/ui-src/src/components/modals/AddEditEntityModal.tsx
  services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
  services/ui-src/src/utils/testing/mockForm.tsx
Labels: ready for review, product review

#637 cmdct-3684 - add missing intro text to closeout section
  services/app-api/forms/wp.json
Labels: ready for review

#639 [CMDCT-3860] - Remove help link from SAR Dashboard accordion
  services/ui-src/src/verbiage/pages/accordion.ts
Labels: ready for review, design review

#640 Fix unmarshaller and kafka handler; add script to re-run kafka sync for malformed records
  services/app-api/serverless.yml
  services/app-api/storage/reports.ts
  services/app-api/utils/constants/constants.ts
  services/app-api/utils/kafka/kafka-source-lib.ts
  services/database/package.json
  services/database/scripts/sync-kafka-2024.js
  services/database/scripts/utils/dynamodb.js
  services/database/scripts/utils/s3.js
  services/database/yarn.lock
Labels: ready for review

#641 [CMDCT-3681] - Update SAR Creation Modal to check only applicable populations
  services/ui-src/src/components/modals/CreateSarModal.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
  services/ui-src/src/utils/forms/forms.test.ts
  services/ui-src/src/utils/forms/forms.ts
  services/ui-src/src/utils/testing/mockEntities.tsx
Labels: ready for review

#643 Adjust SAR dashboard error logic
  services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
  services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
Labels: ready for review

#638 [CMDCT-3693] - Update getLastCreatedWorkPlan to return the oldest workplan thats eligible
  services/app-api/handlers/reports/create.test.ts
  services/app-api/handlers/reports/create.ts
  services/app-api/utils/other/other.test.ts
  services/app-api/utils/other/other.ts
  services/ui-src/src/components/reports/ReportProvider.tsx
  services/ui-src/src/utils/reports/reports.test.ts
  services/ui-src/src/utils/reports/reports.ts
Labels: ready for review

#646 Cmdct 3683 - add divider lines to RET pages
  services/app-api/forms/sar.json
  services/ui-src/src/components/forms/Form.tsx
  services/ui-src/src/components/forms/FormLayoutElements.tsx
Labels: ready for review

#649 Cmdct 3662 - remove button from inside link
  services/ui-src/src/components/layout/Header.tsx
  services/ui-src/src/styles/theme.ts
  tests/cypress/e2e/wp/form.cy.js
Labels: ready for review

#659 Use concurrency to manage action queueing
  .github/github-lock.sh
  .github/workflows/destroy.yml
  run
Labels: ready for review

#652 Format aria labels for PDF table headers
  services/ui-src/src/components/export/ExportedModalDrawerReportSection.test.tsx
  services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
Labels: ready for review, design review

#654 Refactor PDF report headings
  services/ui-src/src/components/cards/EntityCardTopSection.tsx
  services/ui-src/src/components/cards/EntityStepCard.tsx
  services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
  services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/export/ExportedOverlayModalReportSection.tsx
  services/ui-src/src/components/export/ExportedReportFieldTable.tsx
  services/ui-src/src/components/export/ExportedReportWrapper.tsx
  services/ui-src/src/components/export/ExportedSectionHeading.test.tsx
  services/ui-src/src/components/export/ExportedSectionHeading.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
  services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
  services/ui-src/src/types/reports.ts
  services/ui-src/src/utils/testing/mockReport.ts
  services/ui-src/src/verbiage/pages/sar/sar-export.ts
  services/ui-src/src/verbiage/pages/wp/wp-export.ts
Labels: ready for review, design review

#666 Refactor Entity Status Icon
  services/ui-src/src/assets/icons/icon_check_circle_dark.png
  services/ui-src/src/assets/icons/icon_error_circle.png
  services/ui-src/src/assets/icons/icon_error_circle_bright.png
  services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
  services/ui-src/src/components/index.ts
  services/ui-src/src/components/statusing/StatusTable.tsx
  services/ui-src/src/components/tables/EntityRow.tsx
  services/ui-src/src/components/tables/EntityStatusIcon.tsx
  services/ui-src/src/components/tables/getEntityStatus.test.ts
  services/ui-src/src/components/tables/getEntityStatus.tsx
  services/ui-src/src/types/other.ts
Labels: ready for review

#668 Cmdct 3691 - refactor of StatusTable
  services/ui-src/src/components/statusing/ChildRow.test.tsx
  services/ui-src/src/components/statusing/ChildRow.tsx
  services/ui-src/src/components/statusing/EditButton.test.tsx
  services/ui-src/src/components/statusing/EditButton.tsx
  services/ui-src/src/components/statusing/StatusIcon.test.tsx
  services/ui-src/src/components/statusing/StatusIcon.tsx
  services/ui-src/src/components/statusing/StatusTable.test.tsx
  services/ui-src/src/components/statusing/StatusTable.tsx
  services/ui-src/src/components/statusing/TableRow.test.tsx
  services/ui-src/src/components/statusing/TableRow.tsx
  services/ui-src/src/utils/testing/mockForm.tsx
Labels: ready for review

#674 Move deploy script to run
  .github/workflows/deploy.yml
  scripts/deploy.sh
  src/run.ts
Labels: ready for review
